// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2lIaj2znX9WWZ03QvljSJ8_2raNI0fYc',
    appId: '1:955684673260:web:3f629b89d5c97a4347f7c9',
    messagingSenderId: '955684673260',
    projectId: 'fashion-app-7a0c8',
    authDomain: 'fashion-app-7a0c8.firebaseapp.com',
    storageBucket: 'fashion-app-7a0c8.firebasestorage.app',
    measurementId: 'G-HB4N5KBV83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAhpEbhBGqv_Mmg7yfxwzsmMDw1Nh_04I',
    appId: '1:955684673260:android:b44beed5da08f3b147f7c9',
    messagingSenderId: '955684673260',
    projectId: 'fashion-app-7a0c8',
    storageBucket: 'fashion-app-7a0c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4e0j_shC6LA1m2XtVn93aTpJY_SyD29o',
    appId: '1:955684673260:ios:cf7447d3c0bcb88d47f7c9',
    messagingSenderId: '955684673260',
    projectId: 'fashion-app-7a0c8',
    storageBucket: 'fashion-app-7a0c8.firebasestorage.app',
    iosBundleId: 'com.example.fashionStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4e0j_shC6LA1m2XtVn93aTpJY_SyD29o',
    appId: '1:955684673260:ios:cf7447d3c0bcb88d47f7c9',
    messagingSenderId: '955684673260',
    projectId: 'fashion-app-7a0c8',
    storageBucket: 'fashion-app-7a0c8.firebasestorage.app',
    iosBundleId: 'com.example.fashionStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2lIaj2znX9WWZ03QvljSJ8_2raNI0fYc',
    appId: '1:955684673260:web:1072e627ce3fc7b547f7c9',
    messagingSenderId: '955684673260',
    projectId: 'fashion-app-7a0c8',
    authDomain: 'fashion-app-7a0c8.firebaseapp.com',
    storageBucket: 'fashion-app-7a0c8.firebasestorage.app',
    measurementId: 'G-G92EVMXV2Y',
  );
}
